### PR TITLE
Issue 4 - Build parmeter support in play commands

### PR DESCRIPTION
**Pull request by cescoffier**
Fixe the issue-4

Play command can contains build parameter (Variables). They will be substituted. It also fixed a state (shared across executions) issue with the exitCode map.

### CODE REVIEW

**Comment by ikeike443** [comment]
Thanks.
Please wait for a while.
I'll check and release it.

**Comment by cescoffier** [comment]
Sorry, there was a critical bug that I just fixed. Could you re-merged ?

**Comment by ikeike443** [comment]
sure.
No problem.

iPhoneから送信

On 2011/08/17, at 22:43, cescoffier
reply@reply.github.com
wrote:

**Comment by ikeike443** [comment]
The bug you said may be at this point?
List<ParameterValue> values = param.getParameters();

I've fixed it as below:
List<ParameterValue> values = param!=null? param.getParameters() : null;

**Comment by cescoffier** [comment]
Exactly,

It's fixed in my branch.

**Pull request merged**
